### ISSUE TITLE
Use `seqan3::binning_bitvector` instead of `std::vector<uint8_t>` to save memory

### ISSUE THREAD

**Issue by eaasna** [eaasna/sliding-window#14]
I'm trying to create a `std::vector` of binning bitvectors. The table or `std::vector` would only contain [0,1].

What works:
```
std::vector<seqan3::counting_vector<uint8_t>> counting_table;
counting_table.reserve(minimiser.size());

for (auto min : minimiser)
{   
    seqan3::counting_vector<uint8_t> counts(ibf.bin_count(), 0);
    counts += agent.bulk_contains(min);
    counting_table.emplace_back(std::move(counts));
} 
```

What I'm trying to do:
```
std::vector<seqan3::interleaved_bloom_filter< data_layout_mode_ >::membership_agent::binning_bitvector> counting_table;
counting_table.reserve(minimiser.size());

for (auto min : minimiser)
{   
    auto & counts = agent.bulk_contains(min);
    counting_table.emplace_back(std::move(counts));
}       
```

I also tried inferring the type from the output of `agent.bulk_contains()` but that also failed
```
// Option A:
            typedef std::remove_reference<decltype(agent.bulk_contains(0))>::type binning_bitvector;
            std::vector<binning_bitvector> counting_table;

// Option B: 
            using binning_bitvector = typename std::remove_reference<decltype(agent.bulk_contains(0))>::type;
            std::vector<binning_bitvector> counting_table;
            
// Option C:
            std::vector<std::remove_reference<decltype(agent.bulk_contains(0))>::type> counting_table;
```

**Comment by eaasna** [comment]
Error message for option C:
```
error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Alloc> class std::vector’
      std::vector<std::remove_reference<decltype(agent.bulk_contains(0))>::type> counting_table;
```

**Comment by eseiler** [comment]
```cpp
using counting_vector_t = seqan3::counting_vector<uint8_t>;
std::vector<counting_vector_t> counting_table(minimiser.size(), counting_vector_t(ibf.bin_count(), 0));

for (size_t i{0}; i < minimiser.size(); ++i)
    counting_table[i] += agent.bulk_contains(minimiser[i]);
```

The `using` is just for readability.
`counting_table` is initialised with `minimiser.size()` many counting vectors, each of one has `ibf.bin_count()` many entries.

Then we can just iterate over all minimisers and directly `+=` the `bulk_contains` result to the `counting_table`.

**Comment by eaasna** [comment]
Thanks for taking a look @eseiler I was actually looking to avoid using `seqan3::counting_vector<uint8_t>` because my data is basically boolean [0,1] and I thought using the `seqan3::binning_bitvector` could help me save memory. The issue comes in specifying the data type for this https://docs.seqan.de/seqan/3.0.3/classseqan3_1_1interleaved__bloom__filter_1_1membership__agent_1_1binning__bitvector.html binning bitvector

**Comment by eaasna** [comment]
Trying to infer the `binning_bitvector` type
``
            using counting_vector_t = typename std::remove_reference<decltype(agent.bulk_contains(0))>::type;
            std::vector<counting_vector_t> counting_table(minimiser.size(), 
                                   counting_vector_t(ibf.bin_count(), 0));

            for (size_t i{0}; i < minimiser.size(); i++)
            {   
                counting_table[i] = agent.bulk_contains(minimiser[i]);
            }   
```

Error: 
```
error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(__gnu_cxx::new_allocator<_Tp>::const_reference) const [with _Tp = const seqan3::interleaved_bloom_filter<(seqan3::data_layout)1>::membership_agent::binning_bitvector; __gnu_cxx::new_allocator<_Tp>::const_pointer = const seqan3::interleaved_bloom_filter<(seqan3::data_layout)1>::membership_agent::binning_bitvector*; __gnu_cxx::new_allocator<_Tp>::const_reference = const seqan3::interleaved_bloom_filter<(seqan3::data_layout)1>::membership_agent::binning_bitvector&]’ cannot be overloaded
       address(const_reference __x) const _GLIBCXX_NOEXCEPT
```

**Comment by eseiler** [comment]
Thanks for clarifying :)
My previous snippet didn't work, but this does:

```cpp
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/search/dream_index/interleaved_bloom_filter.hpp>

int main()
{
    seqan3::interleaved_bloom_filter ibf{seqan3::bin_count{8u},
                                         seqan3::bin_size{8192u},
                                         seqan3::hash_function_count{2u}};
    ibf.emplace(23, seqan3::bin_index{0u});
    ibf.emplace(23, seqan3::bin_index{3u});
    ibf.emplace(123, seqan3::bin_index{5u});
    ibf.emplace(4, seqan3::bin_index{7u});

    std::vector<uint64_t> const minimiser{23, 123, 4};
    auto && agent = ibf.membership_agent();

    using binning_vector_t = std::remove_cvref_t<decltype(ibf)>::membership_agent::binning_bitvector;
    std::vector<binning_vector_t> counting_table(minimiser.size(),
                                                 binning_vector_t(ibf.bin_count()));

    for (size_t i{0}; i < minimiser.size(); ++i)
        counting_table[i].raw_data() |= agent.bulk_contains(minimiser[i]).raw_data();

    seqan3::debug_stream << counting_table << '\n'; // [[1,0,0,1,0,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1]]
}
```
